# Configuration for the 1-Joint Setup used for friction calibration.
# In this mode, the joints are expected to spin freely.

can_ports: ["can7"]

max_current_A: 2
has_endstop: false
calibration:
    endstop_search_torques_Nm: [-0.22]
    position_tolerance_rad: 0.05
    move_steps: 500
safety_kd: [0.02]
position_control_gains:
    kp: [6]
    kd: [0.03]

home_offset_rad: [0]
initial_position_rad: [0]

hard_position_limits_lower: [-.inf]
hard_position_limits_upper: [.inf]

