can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
calibration:
    endstop_search_torques_Nm: 
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
        - +0.22
        - +0.22
        - -0.22
    position_tolerance_rad: 0.05
    move_steps: 500
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [4, 4, 4, 4, 4, 4, 4, 4, 4]
    kd: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]


#hard_position_limits_lower: [-.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf]
#hard_position_limits_upper: [.inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf]

hard_position_limits_lower:
    - -1.0
    - -1.67
    - -2.8
    - -1.0
    - -1.67
    - -2.8
    - -1.0
    - -1.67
    - -2.7
hard_position_limits_upper:
    - 1.5
    - 1.67
    - 2.8
    - 1.5
    - 1.67
    - 2.8
    - 1.5
    - 1.67
    - 2.8

soft_position_limits_lower:
    - -0.9
    - -1.57
    - -2.7
    - -0.9
    - -1.57
    - -2.7
    - -0.9
    - -1.57
    - -2.7
soft_position_limits_upper:
    - 1.4
    - 1.57
    - 2.7
    - 1.4
    - 1.57
    - 2.7
    - 1.4
    - 1.57
    - 2.7

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - -1.903
    - -1.845
    - 2.242
    - -1.616
    - -1.762
    - 1.996
    - -2.148
    - -2.143
    - 2.152

# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7
    - 0
    - 0.9
    - -1.7

