can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
move_to_position_tolerance_rad: 0.05
calibration:
    endstop_search_torques_Nm: 
        - +0.3
        - +0.3
        - -0.2
        - +0.3
        - +0.3
        - -0.2
        - +0.3
        - +0.3
        - -0.2
    move_steps: 500
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [4, 4, 4, 4, 4, 4, 4, 4, 4]
    kd: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]


hard_position_limits_lower: [-.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf, -.inf]
hard_position_limits_upper: [.inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf, .inf]
home_offset_rad: [0, 0, 0, 0, 0, 0, 0, 0, 0]
initial_position_rad: [0, 0, 0, 0, 0, 0, 0, 0, 0]
